### PR TITLE
Adding a test to report terminations for multiple keeps at once

### PR DESCRIPTION
**Pull request by dimpar**
Refs #446

Adding the functionality to report termination of multiple keeps with one call. This should save transactions cost.

### CODE REVIEW

**Comment by pdyraga** [comment]
I think this code and `function receiveRewards(bytes32[] memory keepIdentifiers) public` should live in `keep-core`'s `Rewards` contract, heh.

**Comment by dimpar** [comment]
Yes, agree, but also just an idea to leave batch processing tests for ecdsa as is here.

Solidity code was moved in this PR https://github.com/keep-network/keep-core/pull/2146 + some additional general tests.

**Comment by pdyraga** [comment]
The test looks very good, I'll wait for https://github.com/keep-network/keep-core/pull/2146 to be merged first and then will merge this one.

**Comment by pdyraga** [comment]
@dimpar Having https://github.com/keep-network/keep-core/pull/2146 merged, I updated the dependency to `keep-core` and merged `master`. Can you please look at my changes?

**Review by pdyraga — APPROVED** [review]

**Comment by dimpar** [comment]
Don't we want to update `package.json` to `1.3.1-pre.4`? Or is the plan to update it later upon deployment of the actual release?

**Comment by pdyraga** [comment]
`package.json` already points to the most recent `-pre`: `"@keep-network/keep-core": ">1.3.1-pre <1.3.1-rc",`

**Comment by dimpar** [comment]
Ah, I didn't pull the latest, now I see. Yes, looks good.

**Pull request merged**
