### PR TITLE
Mainnet bootstraps

### PR DESCRIPTION
**Pull request by pdyraga**
We currently have bootstrap nodes from:
- Boar
- Staked
- Figment

Waiting for Bison and we'll be ready.

### CODE REVIEW

**Comment by pdyraga** [comment]
OK, I am going to remove them for now and confirm with Figment.

**Comment by sthompson22** [comment]
Waiting for green and will merge.

**Comment by alphastorm** [comment]
🔥

**Comment by mattharrop** [comment]
Figment seed nodes fixed.

**Pull request merged**
