### PR TITLE
Update run-keep-ecdsa.adoc with Bison Trails peers

### PR DESCRIPTION
**Pull request by bgapinski-bt**

### CODE REVIEW

**Comment by pdyraga** [comment]
Thank your for the contribution @bgapinski-bt :rocket: Could you please update your PR with the recent `master` version of bootstrap peer list? We are having a conflict here.

**Comment by pdyraga** [comment]
Oops, we have one unsigned commit here and I can't merge without having all commits signed. @bgapinski-bt do you mind rebasing and signing c071f9d?

**Comment by sthompson22** [comment]
@pdyraga Anything we're waiting on here?

**Comment by pdyraga** [comment]
@bgapinski-bt Can you please update your fork with the upstream changes?

**Comment by pdyraga** [comment]
Closing this one in favor of https://github.com/keep-network/keep-ecdsa/pull/582

**Pull request closed without merging**
