### PR TITLE
Automate getting `TBTCSystem` address for pods

### PR DESCRIPTION
**Pull request by lukasz-zimnoch**
This pull request enables the possibility of passing `TBTCSystem.json` directly into the init container script and eliminates the need of passing the `TBTCSystem` address via env variable in pods configs. To make it work, a change in CI jobs order is needed. Specifically we need to have: `keep-ecdsa deploy contracts` -> `tbtc deploy contracts` -> `keep-ecdsa build init container`

### CODE REVIEW

**Comment by nkuba** [comment]
The changes look great! We need to have aforementioned deployment cycle updated in other PR and merge all related PRs together.

**Comment by michalinacienciala** [comment]
> The changes look great! We need to have aforementioned deployment cycle updated in other PR and merge all related PRs together.

PRs with updated cycle:
https://github.com/keep-network/ci/pull/12
https://github.com/keep-network/keep-ecdsa/pull/876

**Review by michalinacienciala — APPROVED** [review]
Looks good to me. Not merging jet, we'll wait for approval on the related PRs and will merge then.

**Comment by nkuba** [comment]
And now we've got conflicts 😿

**Comment by lukasz-zimnoch** [comment]
> And now we've got conflicts 😿

Resolved! 🚀

**Review by nkuba — APPROVED** [review]

**Pull request merged**
